#!/bin/bash
#
# nv-avd-2
#
# chkconfig: 2345 10 90
# description: Android Virtual Device #2.
#

# Source function library.
. /etc/init.d/nv-avd-commons

SERVICE_NAME=nv-avd-2
SERVICE_LOG_FILE=$HOME/$SERVICE_NAME.log
DEVICE_NAME=android-22_google-apis_x86_alt
DEVICE_RESOLUTION=720x1280
ANDROID_SYSTEM_IMAGES="system-images;android-22;google_apis;x86"

create-log-file

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status
	;;
    restart)
	restart
        ;;
    *)
      	log "Usage: $SERVICE_NAME {start|stop|status|restart}"
        exit 1
	;;
esac
exit $?
