#!/bin/bash
#
# nv-avd-2
#
# chkconfig: 2345 10 90
# description: Android Virtual Device #2.
#

SERVICE_NAME=nv-avd-2
DEVICE_NAME=android-22_google-apis_x86_alt
DEVICE_RESOLUTION=720x1280
ANDROID_SYSTEM_IMAGES="system-images;android-22;google_apis;x86"

# Commons util file below need variable SERVICE_NAME, DEVICE_NAME, DEVICE_RESOLUTION and ANDROID_SYSTEM_IMAGES.
. /etc/init.d/nv-avd-commons
