#!/bin/bash
#
# nv-avd-1
#
# chkconfig: 2345 10 90
# description: Android Virtual Device #1.
#

SERVICE_NAME=nv-avd-1
DEVICE_NAME=android-22_google-apis_x86
DEVICE_RESOLUTION=1080x1920
ANDROID_SYSTEM_IMAGES="system-images;android-22;google_apis;x86"

# Commons util file below need variable SERVICE_NAME, DEVICE_NAME, DEVICE_RESOLUTION and ANDROID_SYSTEM_IMAGES.
. /etc/init.d/nv-avd-commons
