#!/bin/bash
#
# nv-appium
#
# chkconfig: 2345 10 90
# description: Run Appium server.
#

# Source function library.
. /etc/init.d/nv-commons

SERVICE_NAME=nv-appium
SERVICE_LOG_FILE=$HOME/$SERVICE_NAME.log
PROGRAM_NAME=Appium
PROGRAM_REGEX="[n]ode.*appium"

create-log-file

start() {
    log "===== STARTING SERVICE \"$SERVICE_NAME\" ====="
    show-info
    find-and-kill-program
    run-appium
    log ""
    log "===== END OF STARTING SERVICE \"$SERVICE_NAME\" ====="
    log ""
}

stop() {
    log "===== SHUTTING DOWN SERVICE \"$SERVICE_NAME\" ====="
    show-info
    find-and-kill-program
    log ""
    log "===== END OF SHUTTING DOWN SERVICE \"$SERVICE_NAME\" ====="
    log ""
}

restart() {
    log "RESTARTING SERVICE \"$SERVICE_NAME\" ..."
    stop
    start
}

status() {
    check-program-status
}

run-appium() {
    # Starting Appium
    RUN_APPIUM_CMD="appium >> $SERVICE_LOG_FILE 2>&1 &"
    log "Run Appium: su - $USER -c \"$RUN_APPIUM_CMD\""
    su - $USER -c "$RUN_APPIUM_CMD"

    # Give time for appium to up and then check the status
    sleep 5
    status
}

show-info() {
    log ""
    log "SERVICE VARIABLES:"
    log "USER=$USER"
    log "HOME=$HOME"
    log "PATH=$PATH"
    log "SERVICE_NAME=$SERVICE_NAME"
    log "SERVICE_LOG_FILE=$SERVICE_LOG_FILE"
    log ""
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        show-usage
        exit 1
        ;;
esac
exit $?
